site_name: yakui - Kubernetes Admin UI
site_description: A comprehensive web-based administration interface for Kubernetes clusters with dark mode support
site_author: yakui Team
site_url: https://brunseba.github.io/yakui/

# Repository
repo_name: yakui
repo_url: https://github.com/brunseba/yakui
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 yakui Team

# Configuration
theme:
  name: material
  logo: images/yakui-overview.png
  favicon: images/yakui-overview.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.highlight
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mermaid2:
      arguments:
        theme: |
          ^(localStorage.getItem('__palette') || 'auto') === 'auto'
          ? 'neutral'
          : (localStorage.getItem('__palette') || 'auto') === 'dark'
          ? 'dark'
          : 'default'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: brunseba
      repo: yakui
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: guides/PHASE1_WEEK1_QUICKSTART.md
    - Task File Guide: guides/TASKFILE_GUIDE.md
    - Git Workflow: guides/GIT_WORKFLOW.md
    - Dependency Browser Guide: guides/DEPENDENCY_BROWSER_GUIDE.md
  - Development:
    - Kubernetes Resource Manager: development/KUBERNETES_RESOURCE_MANAGER_SUMMARY.md
    - RBAC Manager: development/RBAC_MANAGER.md
    - RBAC Detail View: development/RBAC_DETAIL_VIEW_README.md
    - RBAC Development Complete: development/RBAC_DEVELOPMENT_COMPLETE.md
    - Resource Dependency Analysis: development/RESOURCE_DEPENDENCY_ANALYSIS.md
    - Dependency Feature Remediation: development/DEPENDENCY_FEATURE_REMEDIATION_PLAN.md
  - Deployment:
    - Docker Dependencies: deployment/DOCKER_DEPENDENCIES.md
    - Production Deployment: deployment/PRODUCTION_DEPLOYMENT.md
    - Production Checklist: deployment/PRODUCTION_CHECKLIST.md
  - Security:
    - Security Assessment: security/SECURITY_ASSESSMENT.md
    - Hardening & Mitigation Guide: security/HARDENING_MITIGATION_GUIDE.md
    - Security Remediation Plan: security/SECURITY_REMEDIATION_PLAN.md
  - Fixes & Updates:
    - API Base URL Fix: fixes/API_BASE_URL_FIX_SUMMARY.md
    - CRD Details Fix: fixes/CRD_DETAILS_FIX_SUMMARY.md
    - CRD Detail Component: fixes/CRD_DETAIL_COMPONENT_SUMMARY.md
    - Icon Fix: fixes/ICON_FIX_SUMMARY.md
    - Cluster Context Changes: CLUSTER_CONTEXT_CHANGES.md
    - Enhanced CRD Dependencies: ENHANCED_CRD_DEPENDENCIES_SUMMARY.md
    - Substring Fixes: SUBSTRING_FIXES.md
  - Project Info:
    - Implementation Roadmap: IMPLEMENTATION_ROADMAP.md
    - Project Completion: PROJECT_COMPLETION.md
    - Samples: samples.md
  - Changelog: CHANGELOG.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brunseba/yakui
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/brunseba/yakui

# PDF export configuration
extra_css:
  - stylesheets/print.css

# Analytics (optional)
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX